# Network Cycles

In [ ]:
import pandas as pd
import numpy as np
import json

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

path = "/Users/mark/Dropbox/Math/Complex_Systems/research/writeup/graphics/"

In [2]:
#load visitsdf
results_path = "/Users/mark/Desktop/wiki_v4/"
with open(results_path + "clicks.json") as f:
    visits_dict = json.load(f)
visits_df = pd.DataFrame(visits_dict.items())
visits_df.columns = ['article', 'traversal visits']

In [ ]:
#load path length
results_path = "/Users/mark/Desktop/wiki_v4/"
with open(results_path + "ncycles.json") as f:
    nloops_dict = json.load(f)
ncycles_df = pd.DataFrame(nloops_dict.items())
ncycles_df.columns = ['article', 'path length']
ncycles_df = ncycles_df.sort_values(by=['path length'], ascending=False)

# 2-Cycles

## What are the highest-ranking 2-cycles?

In [14]:
#combine lengths and visits dataframes
combined2_df = ncycles_df[ncycles_df['path length'] == 2].merge(visits_df, on='article')
combined2_df = combined2_df[combined2_df['traversal visits'].duplicated(False)]

In [15]:
combined2_df.sort_values(by='traversal visits', ascending=False)

,article,path length,traversal visits
5918,Lecture,2,31000
58203,Presentation,2,31000
23737,Examples of feudalism,2,19280
52724,Feudalism,2,19280
67007,Health care,2,10777
56597,Medical case management,2,10777
19184,BBC,2,8952
47675,Broadcasting House,2,8952
43228,Secondary education,2,7563
36797,Secondary school,2,7563
13436,Dam,2,7043
28743,Reservoir,2,7043
79245,Biological system,2,5574
53676,Biological network,2,5574
80703,Photography,2,4594
11189,Photograph,2,4594
54891,Armenia,2,3948
29388,Hayastan (disambiguation),2,3948
73644,Namibia,2,3800
59233,Angola,2,3800
67098,Malignancy,2,3364
48465,Cancer,2,3364
4762,Web document,2,3140
64113,Web page,2,3140
83395,Jurisdiction (area),2,3122
19652,Jurisdiction,2,3122
7838,Affection,2,3077
13535,Affection (disambiguation),2,3077
62061,Music magazine,2,2589
6688,List of music magazines,2,2589
...,...,...,...
34117,Sponsorship liveries in Formula One,2,0
34116,Anderson-Capner House,2,0
34070,Quartz Hill Airport,2,0
34078,ReUp Records,2,0
34079,"Leaf, Munro",2,0
34080,Operation Minaret,2,0
34081,Armenia at the 2000 Summer Olympics,2,0
34082,Toodyay Historical Society,2,0
34083,Che To,2,0
34088,"Marco Sanudo, Lord of Milos",2,0
34089,SFPA,2,0
34093,"Welda, KS",2,0
34094,Norco (LA),2,0
34095,"Spanish Springs, NV",2,0
34096,Bojera,2,0
34097,"Nikolski, AK",2,0
34099,Evpatoriya,2,0
34100,Indonesia Armed Forces,2,0
34102,"Banks Lake South, WA",2,0
34103,Brethren - Mistery and Wizdm,2,0
34104,Rubaiyat of Omar Khayyám,2,0
34106,Jim-jams,2,0
34107,"Land O Lakes, FL",2,0
34109,"Kingston (CDP), Plymouth County, Massachusetts",2,0
34110,Phillip Abbott,2,0
34111,Onethindi,2,0
34112,"Naked City, Indiana",2,0
34114,"Hari Mandir, Mumbai",2,0
34115,Dissing + Weitling,2,0
83641,Salah El-Din castle,2,0

## Highest-Ranking 2-cycles

In [16]:
combined2_df.sort_values(by=['traversal visits'], ascending=False).head(25)

                         article  path length  traversal visits
5918                     Lecture            2             31000
58203               Presentation            2             31000
23737      Examples of feudalism            2             19280
52724                  Feudalism            2             19280
67007                Health care            2             10777
56597    Medical case management            2             10777
19184                        BBC            2              8952
47675         Broadcasting House            2              8952
43228        Secondary education            2              7563
36797           Secondary school            2              7563
13436                        Dam            2              7043
28743                  Reservoir            2              7043
79245          Biological system            2              5574
53676         Biological network            2              5574
80703                Photography            2              4594
11189                 Photograph            2              4594
54891                    Armenia            2              3948
29388  Hayastan (disambiguation)            2              3948
73644                    Namibia            2              3800
59233                     Angola            2              3800
67098                 Malignancy            2              3364
48465                     Cancer            2              3364
4762                Web document            2              3140
64113                   Web page            2              3140
83395        Jurisdiction (area)            2              3122

### Traversal Visit Distribution of 2-cycles

In [19]:
combined2_df.describe()

       path length  traversal visits
count        83565      83565.000000
mean             2          6.546389
std              0        208.843811
min              2          0.000000
25%              2          0.000000
50%              2          0.000000
75%              2          2.000000
max              2      31000.000000

## Typical 2-cycles

In [18]:
combined2_df[(combined2_df['traversal visits']<15) & (combined2_df['traversal visits']>5)]

,article,path length,traversal visits
8,Uzbekistan Ground Forces,2,10
19,Lanark—Frontenac—Lennox and Addington,2,6
65,Toni Collette & the Finish,2,6
68,Encyclopedia of Popular Music,2,8
70,Cecil Frances Alexander,2,11
71,Raid on Berlin,2,6
82,Richmond International Airport,2,8
100,Carnea,2,6
104,Correspondence principle (disambiguation),2,6
142,Tosiwo Nakayama,2,11
149,APBA Challenge Cup,2,6
150,List of Top Gear episodes,2,6
165,Chris Bohjalian,2,7
179,Hacıqəhrəmanlı,2,6
183,Tsitsernakaberd,2,14
184,Black-tufted marmoset,2,8
225,KRFTech Ltd.,2,6
228,Yazgulyam River,2,10
263,"Kahoku, Ishikawa",2,7
287,Foot whipping,2,13
295,León Cathedral (Nicaragua),2,8
300,List of chess players,2,7
310,Bitburg Air Base,2,6
319,Republic of Namibia,2,8
347,L.B. Landry High School,2,7
349,Henry Cust,2,10
367,Mohammedia,2,11
375,C. D. Batchelor,2,6
428,GTP cyclohydrolase I,2,8
448,Leeds Marsh Lane railway station,2,6
...,...,...,...
83107,Alibi (1931 film),2,9
83122,Feminist Initiative (Sweden),2,8
83128,Coatlicue,2,6
83138,Boyd Gaming,2,6
83148,Dominic Chianese,2,7
83160,Qastina,2,8
83183,Trans-European high-speed rail network,2,14
83213,Ganfyd,2,11
83224,Dzorashen (Maralik),2,7
83255,The Baron in the Trees,2,7
83301,Fotomat,2,8
83318,Photographic image,2,6
83329,Andrew of Crete (martyr),2,7
83343,Sacred natural site,2,7
83362,Dave Myers (chef),2,6
83365,León Cathedral,2,8
83410,Heart Beats (album),2,7
83414,820s BC,2,13
83435,Mattmarksee,2,8
83457,RTÉ Sport,2,11
83458,Father of the Bride (novel),2,8
83489,Austin 12,2,6
83520,Rockville Air Force Station,2,6
83527,Edwin J. Fancey,2,7
83542,"Springfield, Dane County, Wisconsin",2,12
83546,Khün language,2,7
83552,Marquette Golden Eagles,2,13
83579,Saughall Massie,2,9
83618,Lamplugh Inlet,2,7
83624,Bad Eisenkappel,2,10

# 3-cycles

In [22]:
combined3_df = ncycles_df[ncycles_df['path length'] == 3].merge(visits_df, on='article')
combined3_df = combined3_df[combined3_df['traversal visits'].duplicated(False)]
combined3_df.sort_values(by=['traversal visits'], ascending=False)

,article,path length,traversal visits
71197,Balkan peninsula,3,32333
2558,Balkans,3,32333
41373,Southeast Europe,3,32333
29882,Tree of life,3,29302
33929,Tree of life (biology),3,29302
20874,Tree of life (disambiguation),3,29302
10199,Supremacy Clause,3,13968
69587,Article Six of the United States Constitution,3,13968
11563,United States Constitution,3,13968
55358,Telugu cinema,3,4228
74203,Indian cinema,3,4228
51710,Cinema of India,3,4228
49766,Households,3,4150
70624,Dwelling,3,4150
16996,Household,3,4150
45619,Medieval France,3,3262
35935,Kingdom of France,3,3262
10363,France in the Middle Ages,3,3262
53334,Aragatsotn Region,3,3006
34254,Provinces of Armenia,3,3006
12267,Administrative divisions of Armenia,3,3006
64901,Residency,3,2339
51620,Residency (disambiguation),3,2339
67373,Residency (domicile),3,2339
42867,Leonard Jenyns,3,2123
30200,Leonard Blomefield,3,2123
1592,Leonard Bloomfield,3,2123
30269,Women's Tennis Association,3,1674
57575,World number 1 women tennis players,3,1674
70432,Billie Jean King,3,1674
...,...,...,...
28273,"""Na Na (N-Dubz song)",3,0
28311,Museum At Warm Springs,3,0
28274,Gamers grip,3,0
28275,HGC+,3,0
28276,Sax Rohmer bibliography,3,0
28279,Annual Summer Redneck Games,3,0
28280,Battle of wuzhang plains,3,0
28281,Fern Ridge Dam,3,0
28282,Cape Kiwanda,3,0
28283,Omentum majus,3,0
28285,Pot Black Cup,3,0
28286,Malpaso Company,3,0
28289,Hot Boy,3,0
28291,Transcendence (novel),3,0
28292,St Severinus,3,0
28294,Villainesses,3,0
28295,AmerisourceBergen Corp.,3,0
28296,Charlotte of Aragon,3,0
28297,Crisis of 2020,3,0
28298,Fréchet,3,0
28299,Diran of Armenia,3,0
28300,XFire (TV series),3,0
28303,Vijay (1989 film),3,0
28304,Timeline of architectural styles 1750-1900,3,0
28305,Movies.com,3,0
28307,Su Su Su Super Kirei,3,0
28308,Sub-basis,3,0
28309,MacCready (disambiguation),3,0
28310,Momversation,3,0
74280,Nina Zagat,3,0

In [23]:
combined3_df.sort_values(by=['traversal visits'], ascending=False).head(25)

,article,path length,traversal visits
71197,Balkan peninsula,3,32333
2558,Balkans,3,32333
41373,Southeast Europe,3,32333
29882,Tree of life,3,29302
33929,Tree of life (biology),3,29302
20874,Tree of life (disambiguation),3,29302
10199,Supremacy Clause,3,13968
69587,Article Six of the United States Constitution,3,13968
11563,United States Constitution,3,13968
55358,Telugu cinema,3,4228
74203,Indian cinema,3,4228
51710,Cinema of India,3,4228
49766,Households,3,4150
70624,Dwelling,3,4150
16996,Household,3,4150
45619,Medieval France,3,3262
35935,Kingdom of France,3,3262
10363,France in the Middle Ages,3,3262
53334,Aragatsotn Region,3,3006
34254,Provinces of Armenia,3,3006
12267,Administrative divisions of Armenia,3,3006
64901,Residency,3,2339
51620,Residency (disambiguation),3,2339
67373,Residency (domicile),3,2339
42867,Leonard Jenyns,3,2123

### descriptive statistics

In [24]:
combined3_df.describe()

       path length  traversal visits
count        74164      74164.000000
mean             3          6.392549
std              0        297.262024
min              3          0.000000
25%              3          0.000000
50%              3          0.000000
75%              3          0.000000
max              3      32333.000000

### typical 3-cycles

In [25]:
combined3_df[(combined3_df['traversal visits']<15) & (combined3_df['traversal visits']>5)]

,article,path length,traversal visits
27,Lake Solina,3,7
32,Wolf–Hirschhorn syndrome,3,11
36,Shan State Army – South,3,11
81,Houghton Hall,3,9
105,Madame de Montesson,3,6
109,Moa class patrol boat,3,8
169,Iowa Corn Indy 300,3,6
190,Mark Verstegen,3,7
193,Where's George?,3,11
194,Park View School (disambiguation),3,9
238,Point-set topology,3,14
255,Linda Hargrove (songwriter),3,7
294,List of Billboard number-one R&B Songs,3,6
306,"Yenikənd, Goranboy",3,6
327,Soko language,3,7
337,Third-Worldism,3,6
340,Jarell Houston,3,10
341,Charles Mills (1788),3,9
372,Barang (Philippine mythology),3,7
374,Webring,3,6
410,Brainwashed (website),3,7
412,Rinaldo d'Este (1618–1672),3,10
413,Toku Hime,3,7
425,Caniapiscau Reservoir,3,7
440,Mew (Pokémon),3,6
510,NONONO,3,10
528,Monroe High School,3,7
542,Erlenmeyer–Plöchl azlactone and amino-acid syn...,3,14
543,Toma,3,7
547,Ferroics,3,8
...,...,...,...
73540,Separatist feminism,3,10
73546,Transmash (disambiguation),3,6
73612,Ladybower Reservoir,3,8
73635,Ksnyatin,3,7
73656,Ólafur Jóhann Ólafsson,3,8
73684,Dual sector education,3,9
73740,Liberty Belle,3,6
73819,List of hospitals in Pittsburgh,3,6
73881,Sagittal,3,10
73882,Latch Key Kid Album,3,11
73883,Diversion,3,8
73902,St. Cloud Hospital,3,7
73912,Yelü Chucai,3,13
73925,Thomas Starzl,3,6
73946,Via Dolorosa,3,6
73950,Javorník (Jeseník District),3,10
74013,The Ten Gurus of Sikhism,3,13
74078,Skeleton (undead),3,9
74089,Treccani,3,13
74100,Extreme clipper,3,8
74126,Acute erythroid leukemia,3,8
74167,Ubbi dubbi,3,10
74168,Bottlenose skate,3,7
74172,J.R. (musician),3,6
74179,Władysław Opolski,3,12
74181,Circlip,3,7
74193,Givati Brigade,3,7
74204,"Mürsəlli, Imishli",3,8
74248,Lake Jualbup,3,10
74268,Telephoto,3,14

## What are the highest-ranking n-cycles where n < 10 ?

In [28]:
combined10_df = ncycles_df[ncycles_df['path length'] < 10].merge(visits_df, on='article')
combined10_df = combined10_df[combined10_df['traversal visits'].duplicated(False)]
combined10_df.sort_values(by=['traversal visits'], ascending=False)

,article,path length,traversal visits
84383,Quality (philosophy),7,7400884
79486,Reality,7,7400884
75865,Philosophy,7,7400884
82896,Awareness,7,7400884
66245,Existence,7,7400884
68609,Consciousness,7,7400884
73782,Conscious,7,7400884
285891,Southeast Europe,3,32333
315715,Balkan peninsula,3,32333
247076,Balkans,3,32333
324717,Lecture,2,31000
377002,Presentation,2,31000
265392,Tree of life (disambiguation),3,29302
278447,Tree of life (biology),3,29302
274400,Tree of life,3,29302
342536,Examples of feudalism,2,19280
371523,Feudalism,2,19280
256081,United States Constitution,3,13968
254717,Supremacy Clause,3,13968
314105,Article Six of the United States Constitution,3,13968
385806,Health care,2,10777
375396,Medical case management,2,10777
366474,Broadcasting House,2,8952
337983,BBC,2,8952
355596,Secondary school,2,7563
362027,Secondary education,2,7563
347542,Reservoir,2,7043
332235,Dam,2,7043
398044,Biological system,2,5574
372475,Biological network,2,5574
...,...,...,...
156065,Bipolar disorders research,5,0
156063,Container Terminal 4,5,0
156062,Charnage Down Chalk Pit,5,0
156061,Discover Life in America,5,0
156060,Ek erilaz,5,0
156059,Vassil aprilov,5,0
156058,Under 19 Fußball-Bayernliga,5,0
156079,Yoctometer,5,0
156081,Bulgarian Crisis,5,0
156102,Vesselin Petkov Gerov,5,0
156093,Rick holmes,5,0
156101,Democratic union for integration,5,0
156100,Bubblin' (Blue Song),5,0
156099,Draft (sailing),5,0
156098,Political divisions of Serbia and Montenegro,5,0
156097,St. Peters Hospital,5,0
156096,Sabunchi,5,0
156095,Kithakitalu,5,0
156094,Makati Medical Center,5,0
156092,Eugene Major,5,0
156082,Yanek Kuchukov,5,0
156091,Edward de Salisbury,5,0
156090,Order of the cedars,5,0
156089,Harris repertoire,5,0
156088,Zekate House,5,0
156086,Yugoslav Flag,5,0
156085,Vodjani,5,0
156084,List of lakes in Montenegro,5,0
156083,Zeptonewton,5,0
418890,Spyware Quake,1,0

## What are the highest-ranking n-cycles where n < 100?

In [29]:
#runtime > 5min
combined100_df = ncycles_df[ncycles_df['path length'] < 100].merge(visits_df, on='article')
combined100_df = combined100_df[combined100_df['traversal visits'].duplicated(False)]
combined100_df.sort_values(by=['traversal visits'], ascending=False)

,article,path length,traversal visits
7482774,Philosophy,7,7400884
7491292,Quality (philosophy),7,7400884
7473154,Existence,7,7400884
7489805,Awareness,7,7400884
7486395,Reality,7,7400884
7475518,Consciousness,7,7400884
7480691,Conscious,7,7400884
7692800,Southeast Europe,3,32333
7653985,Balkans,3,32333
7722624,Balkan peninsula,3,32333
7731626,Lecture,2,31000
7783911,Presentation,2,31000
5176946,Corporation,27,30777
6778210,Object (physics),22,30777
7685356,Tree of life (biology),3,29302
7681309,Tree of life,3,29302
7672301,Tree of life (disambiguation),3,29302
7778432,Feudalism,2,19280
7749445,Examples of feudalism,2,19280
5136995,Commercial aviation,27,18503
6798972,Beetle,22,18503
6337290,Italic peoples,24,15897
6863004,Kingdom (biology),21,15897
7721014,Article Six of the United States Constitution,3,13968
7662990,United States Constitution,3,13968
7661626,Supremacy Clause,3,13968
1968022,United States Air Force,32,12732
4808785,Auto racing,27,12732
5293482,Payment,26,10915
6397808,Philippines,24,10915
...,...,...,...
2922442,Karosa B 941,30,0
2922441,"Orillia, Ontario",30,0
2922440,The Serenes,30,0
2922439,Dicaeum aeruginosum,30,0
2922467,NNPI-C,30,0
2922468,National Airport,30,0
2922470,Microsoft Windows Desktop Search,30,0
2922471,Martin Holt (fencer),30,0
2922496,All-Ireland Minor Hurling Championship 1983,30,0
2922495,All-Ireland Minor Hurling Championship 1982,30,0
2922494,All-Ireland Minor Hurling Championship 1985,30,0
2922493,All-Ireland Minor Hurling Championship 1984,30,0
2922492,All-Ireland Minor Hurling Championship 1987,30,0
2922491,All-Ireland Minor Hurling Championship 1986,30,0
2922490,All-Ireland Minor Hurling Championship 1989,30,0
2922489,All-Ireland Minor Hurling Championship 1988,30,0
2922488,Co–operative Championship,30,0
2922487,Duratón (river),30,0
2922486,Enduronyl,30,0
2922485,"Turtle Bayou, TX",30,0
2922484,Black-backed Water Tyrant,30,0
2922482,Skrzeszewo Zukowskie,30,0
2922481,Digging in the dirt,30,0
2922479,Infosys China,30,0
2922477,UEFA Champions League 2000–01,30,0
2922476,SFGAm,30,0
2922475,Norwegian Football Cup 1992,30,0
2922473,Francisco Navarro,30,0
2922472,Pump-jet engine,30,0
7825799,Spyware Quake,1,0

## Longest Cycles

In [21]:
ncycles_df.sort(columns=['path length'], ascending=False).head(50)

                                           article  path length
5288899     Holy fathers slain at sinai and raithu          366
2895912    Holly fathers slain at Sinai and Raithu          366
4883441                          Martyrs of Raithu          366
1551427            November 1 (Orthodox Liturgics)          365
7072224                May 16 (Orthodox Liturgics)          365
79906          June 6 (Eastern Orthodox liturgics)          365
1536220          September 17 (Orthodox Liturgics)          365
5425983        July 2 (Eastern Orthodox liturgics)          365
1466458    November 8 (Eastern Orthodox liturgics)          365
4193417      April 12 (Eastern Orthodox liturgics)          365
4168245       June 23 (Eastern Orthodox liturgics)          365
519296               March 31 (Orthodox Liturgics)          365
5610852   February 24 (Eastern Orthodox liturgics)          365
6535420       April 9 (Eastern Orthodox liturgics)          365
6555641       March 5 (Eastern Orthodox liturgics)          365
6949142   September 9 (Eastern Orthodox Liturgics)          365
4814054                May 12 (Orthodox Liturgics)          365
5156184  September 11 (Eastern Orthodox Liturgics)          365
664787   September 19 (Eastern Orthodox Liturgics)          365
344412               April 12 (Orthodox Liturgics)          365
265182         July 8 (Eastern Orthodox liturgics)          365
5263214        May 24 (Eastern Orthodox liturgics)          365
6021620        May 21 (Eastern Orthodox liturgics)          365
7175701                 May 6 (Orthodox Liturgics)          365
196289    November 16 (Eastern Orthodox liturgics)          365
4564722      August 2 (Eastern Orthodox liturgics)          365
1321312  September 29 (Eastern Orthodox Liturgics)          365
3524231               April 1 (Orthodox Liturgics)          365
298945         July 7 (Eastern Orthodox liturgics)          365
6069897              April 10 (Orthodox Liturgics)          365
6762572    October 26 (Eastern Orthodox liturgics)          365
1695347         May 4 (Eastern Orthodox Liturgics)          365
2114395              March 28 (Orthodox Liturgics)          365
2378190     January 5 (Eastern Orthodox liturgics)          365
6917829       July 29 (Eastern Orthodox liturgics)          365
2432379         May 5 (Eastern Orthodox Liturgics)          365
4256101  September 26 (Eastern Orthodox liturgics)          365
625083       August 5 (Eastern Orthodox liturgics)          365
1967630          September 30 (Orthodox Liturgics)          365
7067415        May 15 (Eastern Orthodox Liturgics)          365
2618160              March 23 (Orthodox Liturgics)          365
7217101  September 12 (Eastern Orthodox Liturgics)          365
1461522  September 24 (Eastern Orthodox Liturgics)          365
4608168   February 17 (Eastern Orthodox liturgics)          365
2374928        May 21 (Eastern Orthodox Liturgics)          365
96387    September 14 (Eastern Orthodox Liturgics)          365
6690644      March 27 (Eastern Orthodox liturgics)          365
4436663      April 19 (Eastern Orthodox liturgics)          365
6917119         May 3 (Eastern Orthodox Liturgics)          365
5503298                June 4 (Orthodox Liturgics)          365

### excluding liturgics

In [22]:
l_cycles = ncycles_df.sort(columns=['path length'], ascending=False)
l_cycles[l_cycles['article'].apply(lambda e: "liturgics" not in e.lower())].head(50)

                                         article  path length
5288899   Holy fathers slain at sinai and raithu          366
2895912  Holly fathers slain at Sinai and Raithu          366
4883441                        Martyrs of Raithu          366
5138922   Holy fathers slain at Sinai and Raithu          365
529078      19th Legislative Assembly of Ontario           80
2912756            20th Ontario general election           79
5728652                    1937 Ontario election           79
6600433               19th Parliament of Ontario           79
4786281                          1706 in England           78
7260208           Ontario general election, 1937           78
6797634     20th Legislative Assembly of Ontario           77
2495773                          1704 in England           77
2680445                           1868 in the UK           76
2630950                          1702 in England           76
4203997           Ontario geenral election, 1943           76
2951030               20th Parliament of Ontario           76
529105                     1943 Ontario election           76
4395595            21st Ontario general election           76
4015691           Ontario general election, 1943           75
7254297                          1700 in England           75
3306480                           1866 in the UK           75
7419388               1868 in the United Kingdom           75
3098738     21st Legislative Assembly of Ontario           74
3056095                           1864 in the UK           74
6731327                          1699 in England           74
2003933                          1698 in England           74
518778                1866 in the United Kingdom           74
7364606                           1862 in the UK           73
957060                           1696 in England           73
1011230            22nd Ontario general election           73
4565517                          1697 in England           73
4793936                    1945 Ontario election           73
6163308               1864 in the United Kingdom           73
1191869               21st Parliament of Ontario           73
1690253           Ontario general election, 1945           72
6170080                          1695 in England           72
6719378                          1694 in England           72
3774965                           1860 in the UK           72
3923312               1862 in the United Kingdom           72
5033748     22nd Legislative Assembly of Ontario           71
6531083               1860 in the United Kingdom           71
6851398                          1693 in England           71
2079561                          1692 in England           71
938406                            1858 in the UK           71
2614617                           1856 in the UK           70
4425988               1858 in the United Kingdom           70
6822094               22nd Parliament of Ontario           70
1618088            23rd Ontario general election           70
4877096                          1690 in England           70
6093513                          1691 in England           70

## excluding Liturgics, England, UK, and Ontario

In [23]:
fl_cycles = l_cycles[l_cycles['article'].apply(lambda e: "ontario" not in e.lower())]
fl_cycles = l_cycles[l_cycles['article'].apply(lambda e: "liturgics" not in e.lower())]
fl_cycles = l_cycles[l_cycles['article'].apply(lambda e: "england" not in e.lower())]
fl_cycles = l_cycles[l_cycles['article'].apply(lambda e: "uk" not in e.lower())]
fl_cycles = l_cycles[l_cycles['article'].apply(lambda e: "united kingdom" not in e.lower())]

fl_cycles.head(60)

                                           article  path length
5288899     Holy fathers slain at sinai and raithu          366
2895912    Holly fathers slain at Sinai and Raithu          366
4883441                          Martyrs of Raithu          366
1551427            November 1 (Orthodox Liturgics)          365
7072224                May 16 (Orthodox Liturgics)          365
79906          June 6 (Eastern Orthodox liturgics)          365
1536220          September 17 (Orthodox Liturgics)          365
5425983        July 2 (Eastern Orthodox liturgics)          365
1466458    November 8 (Eastern Orthodox liturgics)          365
4193417      April 12 (Eastern Orthodox liturgics)          365
4168245       June 23 (Eastern Orthodox liturgics)          365
519296               March 31 (Orthodox Liturgics)          365
5610852   February 24 (Eastern Orthodox liturgics)          365
6535420       April 9 (Eastern Orthodox liturgics)          365
6555641       March 5 (Eastern Orthodox liturgics)          365
6949142   September 9 (Eastern Orthodox Liturgics)          365
4814054                May 12 (Orthodox Liturgics)          365
5156184  September 11 (Eastern Orthodox Liturgics)          365
664787   September 19 (Eastern Orthodox Liturgics)          365
344412               April 12 (Orthodox Liturgics)          365
265182         July 8 (Eastern Orthodox liturgics)          365
5263214        May 24 (Eastern Orthodox liturgics)          365
6021620        May 21 (Eastern Orthodox liturgics)          365
7175701                 May 6 (Orthodox Liturgics)          365
196289    November 16 (Eastern Orthodox liturgics)          365
4564722      August 2 (Eastern Orthodox liturgics)          365
1321312  September 29 (Eastern Orthodox Liturgics)          365
3524231               April 1 (Orthodox Liturgics)          365
298945         July 7 (Eastern Orthodox liturgics)          365
6069897              April 10 (Orthodox Liturgics)          365
6762572    October 26 (Eastern Orthodox liturgics)          365
1695347         May 4 (Eastern Orthodox Liturgics)          365
2114395              March 28 (Orthodox Liturgics)          365
2378190     January 5 (Eastern Orthodox liturgics)          365
6917829       July 29 (Eastern Orthodox liturgics)          365
2432379         May 5 (Eastern Orthodox Liturgics)          365
4256101  September 26 (Eastern Orthodox liturgics)          365
625083       August 5 (Eastern Orthodox liturgics)          365
1967630          September 30 (Orthodox Liturgics)          365
7067415        May 15 (Eastern Orthodox Liturgics)          365
2618160              March 23 (Orthodox Liturgics)          365
7217101  September 12 (Eastern Orthodox Liturgics)          365
1461522  September 24 (Eastern Orthodox Liturgics)          365
4608168   February 17 (Eastern Orthodox liturgics)          365
2374928        May 21 (Eastern Orthodox Liturgics)          365
96387    September 14 (Eastern Orthodox Liturgics)          365
6690644      March 27 (Eastern Orthodox liturgics)          365
4436663      April 19 (Eastern Orthodox liturgics)          365
6917119         May 3 (Eastern Orthodox Liturgics)          365
5503298                June 4 (Orthodox Liturgics)          365
6575476    October 11 (Eastern Orthodox liturgics)          365
1934546                May 27 (Orthodox Liturgics)          365
1190329   December 19 (Eastern Orthodox liturgics)          365
6800453  September 22 (Eastern Orthodox Liturgics)          365
592241   September 24 (Eastern Orthodox liturgics)          365
1569375       June 10 (Eastern Orthodox Liturgics)          365
1329727               April 2 (Orthodox Liturgics)          365
3554626         May 4 (Eastern Orthodox liturgics)          365
5448552  September 27 (Eastern Orthodox liturgics)          365
2257707        May 22 (Eastern Orthodox Liturgics)          365